# Use the official Python image as a base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /

# Install dependencies
COPY .requirements.txt requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the rest of the application code to the container
COPY ./app /app

# Expose port 5000 (assuming your Flask app runs on port 5000)
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "./app/app.py"]
